load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "utils_lib",
    srcs = [
        "utils.cpp",
    ],
    hdrs = [
        "utils.h"
    ],
    deps = [],
    visibility = ["//src/dht:__pkg__"],
)
